[global]

# If false, the file watcher will not watch files.
developmentMode = false

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

[client]

# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not draw to a Streamlit app.
displayEnabled = true

# Controls whether uncaught app exceptions are displayed in the browser.
showErrorDetails = true

[runner]

# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
magicEnabled = true

# Install a Python tracer to allow you to stop or pause your script at any point and introspect it.
installTracer = false

# Sets the MPLBACKEND environment variable to Agg inside Streamlit to prevent Python crashing.
fixMatplotlib = true

# Run the Python Garbage Collector after each script execution.
postScriptGC = true

# Handle script rerun requests immediately, rather than waiting for script execution to reach a yield point.
fastReruns = true

[server]

# List of folders that should not be watched for changes.
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this should be set to the same value across all replicas to ensure they all share the same secret.
cookieSecret = "viral-genomics-dashboard-key"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# The address where the server will listen for client and browser connections.
address = "localhost"

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Enables support for Cross-Origin Request Sharing (CORS) protection, for added security.
enableCORS = true

# Enables support for Cross-Site Request Forgery (CSRF) protection, for added security.
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false

[browser]

# Internet address where users should point their browsers in order to connect to the app.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = true

# Configure the ability to share apps to the cloud.
serverPort = 8501

[theme]

# Primary accent color for interactive elements.
primaryColor = "#FF6B6B"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app, except code blocks.
font = "sans serif"
